const CustomerActionTypes = {
  ADMIN_SIGNIN_START: "ADMIN_SIGNIN_START",
  ADMIN_SIGNIN_SUCCESS: "ADMIN_SIGNIN_SUCCESS",
  ADMIN_SIGNIN_FAIL: "ADMIN_SIGNIN_FAIL",

  GET_LOGGED_IN_USER_START: "GET_LOGGED_IN_USER",
  GET_LOGGED_IN_USER_SUCCESS: "GET_LOGGED_IN_USER_SUCCESS",
  GET_LOGGED_IN_USER_FAIL: "GET_LOGGED_IN_USER_FAIL",

  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAIL: "SIGNOUT_FAIL",

  USER_SIGNIN_START: "USER_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",

  REGISTER_USER_START: "REGISTER_USER_START",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",
};

export default CustomerActionTypes;
