const ShopActionTypes = {
  GET_ALL_SHOPS_START: "GET_ALL_SHOPS_START",
  GET_ALL_SHOPS_SUCCESS: "GET_ALL_SHOPS_SUCCESS",
  GET_ALL_SHOPS_FAIL: "GET_ALL_SHOPS_FAIL",

  GET_SINGLE_SHOP_START: "GET_SINGLE_SHOP_START",
  GET_SINGLE_SHOP_SUCCESS: "GET_SINGLE_SHOP_SUCCESS",
  GET_SINGLE_SHOP_FAIL: "GET_SINGLE_SHOP_FAIL",

  UPDATE_SHOP_START: "UPDATE_SHOP_START",
  UPDATE_SHOP_SUCCESS: "UPDATE_SHOP_SUCCESS",
  UPDATE_SHOP_FAIL: "UPDATE_SHOP_FAIL",

  ADD_SHOP_START: "ADD_SHOP_START",
  ADD_SHOP_SUCCESS: "ADD_SHOP_SUCCESS",
  ADD_SHOP_FAIL: "ADD_SHOP_FAIL",

  DELETE_SHOP_START: "DELETE_SHOP_START",
  DELETE_SHOP_SUCCESS: "DELETE_SHOP_SUCCESS",
  DELETE_SHOP_FAIL: "DELETE_SHOP_FAIL",

  ADD_REVIEW_START: "ADD_REVIEW_START",
  DELETE_REVIEW_START: "DELETE_REVIEW_START",
};

export default ShopActionTypes;
