const OrderActionTypes = {
  SAVE_ITEMS: "SAVE_ITEMS",

  SHIPPING_INFO: "SHIPPING_INFO",

  CREATE_ORDER_START: "CREATE_ORDER_START",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

  FETCH_MY_ORDERS_START: "FETCH_MY_ORDERS_START",
  FETCH_MY_ORDERS_SUCCESS: "FETCH_MY_ORDERS_SUCCESS",
  FETCH_MY_ORDERS_FAIL: "FETCH_MY_ORDERS_FAIL",

  FETCH_ORDER_DETAILS_START: "FETCH_ORDER_DETAILS_START",
  FETCH_ORDER_DETAILS_SUCCESS: "FETCH_ORDER_DETAILS_SUCCESS",
  FETCH_ORDER_DETAILS_FAIL: "FETCH_ORDER_DETAILS_FAIL",

  FETCH_ALL_ORDERS_START: "FETCH_ALL_ORDERS_START",
  FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
  FETCH_ALL_ORDERS_FAIL: "FETCH_ALL_ORDERS_FAIL",

  UPDATE_ORDER_START: "UPDATE_ORDER_START",
  UPDATE_ORDER_SUCCESS: "UPDATE_ORDER_SUCCESS",
  UPDATE_ORDER_FAIL: "UPDATE_ORDER_FAIL",
};

export default OrderActionTypes;
