const AgentActionTypes = {
  GET_ALL_AGENTS_START: "GET_ALL_AGENTS_START",
  GET_ALL_AGENTS_SUCCESS: "GET_ALL_AGENTS_SUCCESS",
  GET_ALL_AGENTS_FAIL: "GET_ALL_AGENTS_FAIL",

  GET_SINGLE_AGENT_START: "GET_SINGLE_AGENT_START",
  GET_SINGLE_AGENT_SUCCESS: "GET_SINGLE_AGENT_SUCCESS",
  GET_SINGLE_AGENT_FAIL: "GET_SINGLE_AGENT_FAIL",

  UPDATE_AGENT_START: "UPDATE_AGENT_START",
  UPDATE_AGENT_SUCCESS: "UPDATE_AGENT_SUCCESS",
  UPDATE_AGENT_FAIL: "UPDATE_AGENT_FAIL",

  ADD_AGENT_START: "ADD_AGENT_START",
  ADD_AGENT_SUCCESS: "ADD_AGENT_SUCCESS",
  ADD_AGENT_FAIL: "ADD_AGENT_FAIL",

  DELETE_AGENT_START: "DELETE_AGENT_START",
  DELETE_AGENT_SUCCESS: "DELETE_AGENT_SUCCESS",
  DELETE_AGENT_FAIL: "DELETE_AGENT_FAIL",
};

export default AgentActionTypes;
